namespace: /lbs

service-1:
    defines: runnable
    inherits: nginx/latest
    variables:
        defines: variables
        listen-port: 8080

service-2:
    defines: runnable
    inherits: nginx/latest
    variables:
        defines: variables
        listen-port: 8080

services:
    defines: process-group
    balancers:
        defines: balancers
        app-balancer:
            type: http
            port: 8080
            instances:
                - lbs/service-1
                - lbs/service-2

    runnable-list:
        - lbs/service-1
        - lbs/service-2